<?xml version="1.0" encoding="utf-8"?><Database Name="NationalCriminalDb" Class="NationalCriminalDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=NationalCriminalDb;Integrated Security=True" SettingsObjectName="DataObjects.Properties.Settings" SettingsPropertyName="NationalCriminalDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Criminal" Member="Criminals">
    <Type Name="Criminal">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>